source 'http://rubygems.org'
gem 'cucumber'
gem 'rspec'
gem 'ffi'
gem 'watir-webdriver', '>= 0.9.9'
gem 'watir', '>= 6.2.1'
gem 'selenium-webdriver', '>= 3.4.0'
gem 'headless'
gem 'titleize'
gem 'json'
gem 'gherkin'
gem 'syntax'
