source 'http://rubygems.org'
gem 'cucumber'
gem 'rspec'
gem 'ffi'
gem 'watir-webdriver'
gem 'watir'
gem 'selenium-webdriver'
gem 'headless'
gem 'titleize'
gem 'json', '>= 2.3.0'
gem 'gherkin'
gem 'syntax'
